name: LLM Test Suite

on:
  push:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install allure-pytest

      - name: Run tests with Allure
        run: pytest -v --alluredir=playwright-test-results/allure-results

  publish-results:
    needs: run-tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: latest-test-results

      - name: Build Allure report
        uses: simple-elf/allure-report-action@v1.11
        if: always()
        with:
          gh_pages: latest-test-results
          allure_history: allure-history
          allure_results: playwright-test-results/allure-results

      - name: Publish report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history
